### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by juliakozlovsky** [OpenBEL/bel.rb#123] opened 2016-05-16 11:51 UTC
/usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/monkey_patch.rb:16:in `to_rdf_vocabulary': undefined method `end_with?' for nil:NilClass (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/monkey_patch.rb:35:in `to_uri'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/monkey_patch.rb:59:in `to_rdf'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/monkey_patch.rb:172:in `block in to_rdf'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/monkey_patch.rb:171:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/monkey_patch.rb:171:in `to_rdf'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/monkey_patch.rb:236:in `to_rdf'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/monkey_patch.rb:354:in `to_rdf'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/translator.rb:83:in `block (2 levels) in write_rdf_to_io'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/bel_script/evidence_yielder.rb:29:in `block in each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/script.rb:65381:in `block in each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/nonblocking_io_wrapper.rb:25:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/script.rb:63742:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/bel_script/evidence_yielder.rb:24:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/bel_script/evidence_yielder.rb:24:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/translator.rb:72:in `block in write_rdf_to_io'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/translator.rb:111:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/translator.rb:111:in `each'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/translator.rb:111:in `write_rdf_to_io'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translator/plugins/rdf/translator.rb:33:in `write'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/lib/bel/translate.rb:53:in `translate'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/bin/bel2rdf.rb:108:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/bin/bel:103:in `require_relative'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/bin/bel:103:in `run'
        from /usr/local/rvm/gems/ruby-2.3.0/gems/bel-0.7.0/bin/bel:583:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/bel:23:in `load'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/bel:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'bv

**Comment by abargnesi** [comment] 2016-05-18 14:46
Thanks for the report. It is helpful to the community to supply a [short, self contained, correct example](http://www.sscce.org/) for the issue.

**Comment by abargnesi** [comment] 2016-05-18 14:47
It is helpful to supply context around how the error arose.

**Comment by juliakozlovsky** [comment] 2016-05-18 14:56
Yes - currently waiting for the example from the colleagues who found the error..

**Comment by abargnesi** [comment] 2016-05-18 14:57
Thanks!

**Comment by abargnesi** [comment] 2016-05-18 19:33
@sanea's fix was merged into next. Let me know if the fix addresses the original issue.

If so we can merge to master and release a *0.7.1*.

**Comment by sanea** [comment] 2016-05-19 18:34
The issue is reproduced when the prefix of parameter inside bel term contains wrong value. The prefix of the namespace is case sensetive.

#125 is fixing this issue and conversion is working with wrong namepsace prefixes.

[small_corpus_updated.zip](https://github.com/OpenBEL/bel.rb/files/273192/small_corpus_updated.zip)
```
##################################################################################
# Document Properties Section

SET DOCUMENT Name = "BEL Framework Small Corpus Document (updated)"
SET DOCUMENT Description = "Approximately 2000 hand curated statements drawn from 57 PubMeds."
SET DOCUMENT Version = 20131211
SET DOCUMENT Copyright = "Copyright (c) 2011-2012, Selventa. All Rights Reserved."
SET DOCUMENT Authors = Selventa
SET DOCUMENT Licenses = "Creative Commons Attribution-Non-Commercial-ShareAlike 3.0 Unported License"
SET DOCUMENT ContactInfo = "support@belframework.org"

##################################################################################
# Definitions Section

DEFINE NAMESPACE GOBP AS URL "http://resource.belframework.org/belframework/20131211/namespace/go-biological-process.belns"
DEFINE NAMESPACE MESHD AS URL "http://resource.belframework.org/belframework/20131211/namespace/mesh-diseases.belns"

DEFINE ANNOTATION Anatomy AS URL "http://resource.belframework.org/belframework/20131211/annotation/anatomy.belanno"
DEFINE ANNOTATION Disease AS URL "http://resource.belframework.org/belframework/20131211/annotation/disease.belanno"
DEFINE ANNOTATION TextLocation AS LIST {"Abstract","Results","Legend","Review"}

##################################################################################
# Statements Section

SET STATEMENT_GROUP = "Group 1"

SET Disease = atherosclerosis
SET Anatomy = artery
SET TextLocation = Review
SET Evidence = "Oxidation and nitration of macromolecules, such as proteins, DNA and lipids, are prominent
in atherosclerotic arteries."
SET Citation = {"PubMed","Trends in molecular medicine","12928037","","de Nigris F|Lerman A|Ignarro LJ|Williams-Ignarro S|Sica V|Baker AH|Lerman LO|Geng YJ|Napoli C",""}

pathology(meshd:Atherosclerosis) positiveCorrelation biologicalProcess(gobp:"lipid oxidation")
pathology(meshd:Atherosclerosis) positiveCorrelation biologicalProcess(gobp:"protein oxidation")


UNSET STATEMENT_GROUP


```

**Closed** 2016-08-03 15:37 UTC
